name: Publish release

on:
  push:
    branches:
      - 'next'

jobs:
  publish-tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          xcb: 'false'
          wayland: 'true'
      - uses: ./.github/actions/meson
        with:
          cc: gcc
          xcb: 'disabled'
          wayland: 'enabled'
      - uses: ./.github/actions/release
